config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  resources :users, only: [:index, :show, :destroy]
  get 'comments/create'
  resources :families do
  resources :comments
end
  resources :brides
  resources :grooms
  # mount LetterOpenerWeb::Engine, at: "/letter_opener"
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/bride.rb
class Bride < ApplicationRecord
  has_one :groom
  validates :name, :email, :birth_date, :gender, :country, :district, :sector, :cell, :phone, presence: true
end

app/controllers/brides_controller.rb
class BridesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_bride, only: [:show, :edit, :update, :destroy]

  def index
    @brides = Bride.all
  end
  def show
  end
  def new
    @bride = Bride.new
  end
  def edit
  end
  def create
    @bride = Bride.new(bride_params)
      if @bride.save
        redirect_to @bride, notice: 'Bride was successfully created.'
      else
        render :new
      end
  end
  def update
      if @bride.update(bride_params)
        redirect_to @bride, notice: 'Bride was successfully updated.'
      else
        render :edit
      end
  end

  def destroy
    @bride.destroy
    redirect_to brides_url, notice: 'Bride was successfully destroyed.'
  end

  private
    def set_bride
      @bride = Bride.find(params[:id])
    end

    def bride_params
      params.require(:bride).permit(:name, :email, :birth_date, :gender, :country, :district, :sector, :cell, :phone)
    end
end

app/helpers/brides_helper.rb
module BridesHelper
end

app/views/brides/_form.html.erb
<%= form_with(model: bride, local: true) do |form| %>
  <% if bride.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bride.errors.count, "error") %> prohibited this bride from being saved:</h2>

      <ul>
        <% bride.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :birth_date %>
    <%= form.date_select :birth_date %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :district %>
    <%= form.text_field :district %>
  </div>

  <div class="field">
    <%= form.label :sector %>
    <%= form.text_field :sector %>
  </div>

  <div class="field">
    <%= form.label :cell %>
    <%= form.text_field :cell %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/brides/edit.html.erb
<h1>Editing Bride</h1>

<%= render 'form', bride: @bride %>

<%= link_to 'Show', @bride %> |
<%= link_to 'Back', brides_path %>

app/views/brides/index.html.erb
<h1>Brides</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Birth date</th>
      <th>Gender</th>
      <th>Country</th>
      <th>District</th>
      <th>Sector</th>
      <th>Cell</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @brides.each do |bride| %>
      <tr>
        <td><%= bride.name %></td>
        <td><%= bride.email %></td>
        <td><%= bride.birth_date %></td>
        <td><%= bride.gender %></td>
        <td><%= bride.country %></td>
        <td><%= bride.district %></td>
        <td><%= bride.sector %></td>
        <td><%= bride.cell %></td>
        <td><%= bride.phone %></td>
        <td><%= link_to 'Show', bride %></td>
        <td><%= link_to 'Edit', edit_bride_path(bride) %></td>
        <td><%= link_to 'Destroy', bride, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bride', new_bride_path %>

app/views/brides/new.html.erb
<h1>New Bride</h1>

<%= render 'form', bride: @bride %>

<%= link_to 'Back', brides_path %>

app/views/brides/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @bride.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @bride.email %>
</p>

<p>
  <strong>Birth date:</strong>
  <%= @bride.birth_date %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @bride.gender %>
</p>

<p>
  <strong>Country:</strong>
  <%= @bride.country %>
</p>

<p>
  <strong>District:</strong>
  <%= @bride.district %>
</p>

<p>
  <strong>Sector:</strong>
  <%= @bride.sector %>
</p>

<p>
  <strong>Cell:</strong>
  <%= @bride.cell %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @bride.phone %>
</p>

<%= link_to 'Edit', edit_bride_path(@bride) %> |
<%= link_to 'Back', brides_path %>