config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  resources :users, only: [:index, :show, :destroy]
  get 'comments/create'
  resources :families do
  resources :comments
end
  resources :brides
  resources :grooms
  # mount LetterOpenerWeb::Engine, at: "/letter_opener"
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :family
  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post
  before_action :find_comment, only: [:destroy, :edit , :update]

  def index
    @comments = Comment.all
  end
  def create
    @comment = @family.comments.create(params[:comment].permit(:content))
    @comment.save
    if @comment.save
      redirect_to family_path(@family)
    else
      redirect_to family_path(@family), alert: 'Please enter the comment!!!!!'
    end
  end
  def destroy
    @comment.destroy
    redirect_to family_path(@family)
  end
  def edit
  end
  def update
    if @comment.update(params[:comment].permit(:content))
      redirect_to family_path(@family)
    else
      render 'edit'
    end
  end
  private
  def find_post
    @family = Family.find(params[:family_id])
  end
  def find_comment
    @comment = @family.comments.find(params[:id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
  <strong>Comments</strong><br>
  <% @comments.each do |comment| %>
    <% if comment.id.present? %>
        <small><%= comment.content %><br>
        <%= link_to "delete", [comment.family, comment], method: :delete, class:"genric-btn danger-border circle" %>
        <%= link_to "edit ", edit_family_comment_path(comment.family, comment), class:"genric-btn success-border circle" %>
      </small><br>
    <% end %>
  <% end %>
<%= render 'comments/form'%>

app/views/comments/_form.html.erb
<%= form_for ([@family, @family.comments.build]) do |f| %>
<% if @family.errors.any? %>
    <div id="alert-danger">
      <h2><%= pluralize(@family.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% @family.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= f.text_area :content, class:"single-input", placeholder:"enter comment"%>
<%= f.submit "Add comment", class:"genric-btn info-border circle" %>
<% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/edit.html.erb
<%= form_for ([@family, @comment]) do |f| %>
    <%= f.text_area :content, class:"single-input"%>
    <%= f.submit "family comment", class:"genric-btn info-border circle" %>
      <%end%>

app/views/comments/index.html.erb
<h3>comments</h3>