config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  resources :users, only: [:index, :show, :destroy]
  get 'comments/create'
  resources :families do
  resources :comments
end
  resources :brides
  resources :grooms
  # mount LetterOpenerWeb::Engine, at: "/letter_opener"
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/family.rb
class Family < ApplicationRecord
  belongs_to :groom
  has_many :comments, dependent: :destroy
  validates :category, presence: true
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_family, only: [:show, :edit, :update, :destroy]

  def index
    @families = Family.all
  end
  def show
    @comment = @family.comments.build
    @comments = Comment.where(family_id: @family)
  end
  def new
    @family = Family.new
  end
  def edit
  end
  def create
    @family = Family.new(family_params)
      if @family.save
        redirect_to @family, notice: 'Family was successfully created.'
      else
        render :new
      end
  end
  def update
      if @family.update(family_params)
        redirect_to @family, notice: 'Family was successfully updated.'
      else
        render :edit
      end
  end
  def destroy
    @family.destroy
      redirect_to families_url, notice: 'Family was successfully destroyed.'
  end

  private
    def set_family
      @family = Family.find(params[:id])
    end

    def family_params
      params.require(:family).permit(:category, :groom_id)
    end
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/views/families/_form.html.erb
<%= form_with(model: family, local: true) do |form| %>
  <% if family.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(family.errors.count, "error") %> prohibited this family from being saved:</h2>

      <ul>
        <% family.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category %>
    <%= form.number_field :category %>
  </div>



  <div class="field">
    <%= form.label :groom %>
    <%= form.collection_select :groom_id, Groom.order(:name),:id,:name, include_blank: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/families/edit.html.erb
<h1>Editing Family</h1>

<%= render 'form', family: @family %>

<%= link_to 'Show', @family %> |
<%= link_to 'Back', families_path %>

app/views/families/index.html.erb
<h1>Families</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Groom</th>
      <th>Bride</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @families.each do |family| %>
      <tr>
        <td><%= family.category %></td>
        <td><%= family.groom.name%></td>
        <td><%= family.groom.bride.name %></td>
        <td><%= link_to 'Show', family %></td>
        <td><%= link_to 'Edit', edit_family_path(family) %></td>
        <td><%= link_to 'Destroy', family, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Family', new_family_path %>

app/views/families/new.html.erb
<h1>New Family</h1>

<%= render 'form', family: @family %>

<%= link_to 'Back', families_path %>

app/views/families/show.html.erb
  <strong>Category:</strong>
  <%= @family.category %>
</p>

<p>
  <strong>Groom:</strong>
  <%= @family.groom_id %>
</p>

<p>
  <strong>Bride:</strong>
  <%= @family.bride_id %>
</p>
<%= render'comments/comment' %>
<%= link_to 'Edit', edit_family_path(@family) %> |
<%= link_to 'Back', families_path %>