config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  resources :users, only: [:index, :show, :destroy]
  get 'comments/create'
  resources :families do
  resources :comments
end
  resources :brides
  resources :grooms
  # mount LetterOpenerWeb::Engine, at: "/letter_opener"
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/groom.rb
class Groom < ApplicationRecord
  belongs_to :bride
  has_one :family
  validates :name, :email, :birth_date, :gender, :country, :district, :sector, :cell, :phone, presence: true
end

app/controllers/grooms_controller.rb
class GroomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_groom, only: [:show, :edit, :update, :destroy]

  def index
    @q = Groom.ransack(params[:q])
    @grooms = @q.result(distinct: true)
  end

  def show
  end

  def new
    @groom = Groom.new
  end

  def edit
  end
  def create
    @groom = Groom.new(groom_params)

      if @groom.save
        redirect_to @groom, notice: 'Groom was successfully created.'
      else
        render :new
      end
  end
  def update
      if @groom.update(groom_params)
        redirect_to @groom, notice: 'Groom was successfully updated.'
      else
        render :edit
      end
  end

  def destroy
    @groom.destroy
      redirect_to grooms_url, notice: 'Groom was successfully destroyed.'
  end

  private
    def set_groom
      @groom = Groom.find(params[:id])
    end

    def groom_params
      params.require(:groom).permit(:name, :email, :birth_date, :gender, :country, :district, :sector, :cell, :phone, :bride_id)
    end
end

app/helpers/grooms_helper.rb
module GroomsHelper
end

app/views/grooms/_form.html.erb
<%= form_with(model: groom, local: true) do |form| %>
  <% if groom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(groom.errors.count, "error") %> prohibited this groom from being saved:</h2>

      <ul>
        <% groom.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :birth_date %>
    <%= form.date_select :birth_date %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :district %>
    <%= form.text_field :district %>
  </div>

  <div class="field">
    <%= form.label :sector %>
    <%= form.text_field :sector %>
  </div>

  <div class="field">
    <%= form.label :cell %>
    <%= form.text_field :cell %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :bride %>
    <%= form.collection_select :bride_id, Bride.order(:name),:id,:name, include_blank: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/grooms/edit.html.erb
<h1>Editing Groom</h1>

<%= render 'form', groom: @groom %>

<%= link_to 'Show', @groom %> |
<%= link_to 'Back', grooms_path %>

app/views/grooms/index.html.erb
<h1>Grooms</h1>
<div class="col-lg-3 col-md-6">
  <%= search_form_for @q do |f| %>
  <%= f.search_field :name_cont,class:"form-control my-0 py-0 search",placeholder:'Search', style:"float:left" %>
    <button class="btn btn-sm btn-info ml-2 px-2">
      <i class="fa fa-search"></i>
    </button>
  <% end %>
</div>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Birth date</th>
      <th>Gender</th>
      <th>Country</th>
      <th>District</th>
      <th>Sector</th>
      <th>Cell</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @grooms.each do |groom| %>
      <tr>
        <td><%= groom.name %></td>
        <td><%= groom.email %></td>
        <td><%= groom.birth_date %></td>
        <td><%= groom.gender %></td>
        <td><%= groom.country %></td>
        <td><%= groom.district %></td>
        <td><%= groom.sector %></td>
        <td><%= groom.cell %></td>
        <td><%= groom.phone %></td>
        <td><%= link_to 'Show', groom %></td>
        <td><%= link_to 'Edit', edit_groom_path(groom) %></td>
        <td><%= link_to 'Destroy', groom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Groom', new_groom_path %>

app/views/grooms/new.html.erb
<h1>New Groom</h1>

<%= render 'form', groom: @groom %>

<%= link_to 'Back', grooms_path %>

app/views/grooms/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @groom.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @groom.email %>
</p>

<p>
  <strong>Birth date:</strong>
  <%= @groom.birth_date %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @groom.gender %>
</p>

<p>
  <strong>Country:</strong>
  <%= @groom.country %>
</p>

<p>
  <strong>District:</strong>
  <%= @groom.district %>
</p>

<p>
  <strong>Sector:</strong>
  <%= @groom.sector %>
</p>

<p>
  <strong>Cell:</strong>
  <%= @groom.cell %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @groom.phone %>
</p>

<%= link_to 'Edit', edit_groom_path(@groom) %> |
<%= link_to 'Back', grooms_path %>